/* Generated by Yosys 0.19+36 (git sha1 30a4218f537, clang 6.0.0-1ubuntu2 -fPIC -Os) */

(* top =  1  *)
(* src = "iiitb_vm.v:1.1-124.10" *)
module iiitb_vm(change, out, in, clock, reset);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  (* onehot = 32'd1 *)
  wire [6:0] c_state;
  (* src = "iiitb_vm.v:1.34-1.40" *)
  output [1:0] change;
  wire [1:0] change;
  (* src = "iiitb_vm.v:1.78-1.83" *)
  input clock;
  wire clock;
  (* src = "iiitb_vm.v:1.68-1.70" *)
  input [1:0] in;
  wire [1:0] in;
  (* src = "iiitb_vm.v:1.52-1.55" *)
  output out;
  wire out;
  (* src = "iiitb_vm.v:1.90-1.95" *)
  input reset;
  wire reset;
  sky130_fd_sc_hd__nor2_1 _21_ (
    .A(c_state[3]),
    .B(c_state[2]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nor2_1 _22_ (
    .A(c_state[1]),
    .B(c_state[0]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__nand2_1 _23_ (
    .A(_07_),
    .B(_08_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nor3_1 _24_ (
    .A(in[1]),
    .B(in[0]),
    .C(reset),
    .Y(_10_)
  );
  sky130_fd_sc_hd__nand2_1 _25_ (
    .A(_09_),
    .B(_10_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__a211oi_1 _26_ (
    .A1(in[1]),
    .A2(in[0]),
    .B1(reset),
    .C1(c_state[5]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__nand2_1 _27_ (
    .A(_11_),
    .B(_12_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__or2_2 _28_ (
    .A(c_state[1]),
    .B(c_state[3]),
    .X(out)
  );
  sky130_fd_sc_hd__clkinv_1 _29_ (
    .A(c_state[4]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nor2_1 _30_ (
    .A(in[1]),
    .B(reset),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nand2_1 _31_ (
    .A(_14_),
    .B(in[0]),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nor3b_1 _32_ (
    .A(in[0]),
    .B(reset),
    .C_N(in[1]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _33_ (
    .A1_N(_16_),
    .A2_N(_09_),
    .B1(_13_),
    .B2(_15_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__clkinv_1 _34_ (
    .A(c_state[6]),
    .Y(_17_)
  );
  sky130_fd_sc_hd__clkinv_1 _35_ (
    .A(reset),
    .Y(_18_)
  );
  sky130_fd_sc_hd__nand3b_1 _36_ (
    .A_N(in[0]),
    .B(_18_),
    .C(in[1]),
    .Y(_19_)
  );
  sky130_fd_sc_hd__o22ai_1 _37_ (
    .A1(_13_),
    .A2(_19_),
    .B1(_17_),
    .B2(_15_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__clkinv_1 _38_ (
    .A(_07_),
    .Y(change[0])
  );
  sky130_fd_sc_hd__clkinv_1 _39_ (
    .A(_10_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__nor2_1 _40_ (
    .A(_17_),
    .B(_20_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__a21oi_1 _41_ (
    .A1(_07_),
    .A2(_08_),
    .B1(_15_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__nor2_1 _42_ (
    .A(_17_),
    .B(_19_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nor2_1 _43_ (
    .A(_13_),
    .B(_20_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__buf_1 _44_ (
    .A(c_state[5]),
    .X(change[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _45_ (
    .CLK(clock),
    .D(_04_),
    .Q(c_state[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _46_ (
    .CLK(clock),
    .D(_05_),
    .Q(c_state[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _47_ (
    .CLK(clock),
    .D(_00_),
    .Q(c_state[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _48_ (
    .CLK(clock),
    .D(_01_),
    .Q(c_state[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _49_ (
    .CLK(clock),
    .D(_02_),
    .Q(c_state[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _50_ (
    .CLK(clock),
    .D(_03_),
    .Q(c_state[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _51_ (
    .CLK(clock),
    .D(_06_),
    .Q(c_state[6])
  );
endmodule
