/* Generated by Yosys 0.19+36 (git sha1 30a4218f537, clang 6.0.0-1ubuntu2 -fPIC -Os) */

(* top =  1  *)
(* src = "iiitb_vm.v:1.1-82.10" *)
module iiitb_vm(clk, rst, in, out, change);
  (* src = "iiitb_vm.v:12.1-81.4" *)
  wire [1:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  (* force_downto = 32'd1 *)
  (* src = "iiitb_vm.v:0.0-0.0|iiitb_vm.v:22.1-80.8|/usr/local/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [1:0] _38_;
  (* src = "iiitb_vm.v:6.17-6.23" *)
  output [1:0] change;
  wire [1:0] change;
  (* src = "iiitb_vm.v:2.7-2.10" *)
  input clk;
  wire clk;
  (* src = "iiitb_vm.v:4.12-4.14" *)
  input [1:0] in;
  wire [1:0] in;
  (* onehot = 32'd1 *)
  (* unused_bits = "0" *)
  wire [2:0] n_state;
  (* src = "iiitb_vm.v:5.12-5.15" *)
  output out;
  wire out;
  (* src = "iiitb_vm.v:3.7-3.10" *)
  input rst;
  wire rst;
  sky130_fd_sc_hd__clkinv_1 _39_ (
    .A(n_state[2]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__nor3_1 _40_ (
    .A(rst),
    .B(n_state[1]),
    .C(_02_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__and2_2 _41_ (
    .A(in[0]),
    .B(in[1]),
    .X(_04_)
  );
  sky130_fd_sc_hd__nand2_1 _42_ (
    .A(_03_),
    .B(_04_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__clkinv_1 _43_ (
    .A(in[1]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__o21bai_1 _44_ (
    .A1(n_state[2]),
    .A2(n_state[1]),
    .B1_N(rst),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nand3_1 _45_ (
    .A(_07_),
    .B(in[0]),
    .C(_06_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__clkinv_1 _46_ (
    .A(n_state[1]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nor2_1 _47_ (
    .A(rst),
    .B(_09_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__nand2_1 _48_ (
    .A(_10_),
    .B(n_state[2]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nand3_1 _49_ (
    .A(_05_),
    .B(_08_),
    .C(_11_),
    .Y(_00_[0])
  );
  sky130_fd_sc_hd__clkinv_1 _50_ (
    .A(in[0]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__nand3_1 _51_ (
    .A(_07_),
    .B(_12_),
    .C(in[1]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nand3_1 _52_ (
    .A(_03_),
    .B(in[0]),
    .C(_06_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__o21ai_0 _53_ (
    .A1(n_state[2]),
    .A2(_04_),
    .B1(_10_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nand3_1 _54_ (
    .A(_14_),
    .B(_15_),
    .C(_13_),
    .Y(_00_[1])
  );
  sky130_fd_sc_hd__clkinv_1 _55_ (
    .A(change[0]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__nor3b_1 _56_ (
    .A(n_state[2]),
    .B(rst),
    .C_N(n_state[1]),
    .Y(_17_)
  );
  sky130_fd_sc_hd__o21ai_0 _57_ (
    .A1(rst),
    .A2(_16_),
    .B1(in[0]),
    .Y(_18_)
  );
  sky130_fd_sc_hd__nand3_1 _58_ (
    .A(_18_),
    .B(in[1]),
    .C(_17_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__nand2_1 _59_ (
    .A(_06_),
    .B(in[0]),
    .Y(_20_)
  );
  sky130_fd_sc_hd__nand2_1 _60_ (
    .A(_12_),
    .B(in[1]),
    .Y(_21_)
  );
  sky130_fd_sc_hd__o21ai_0 _61_ (
    .A1(rst),
    .A2(_16_),
    .B1(in[1]),
    .Y(_22_)
  );
  sky130_fd_sc_hd__nand4_1 _62_ (
    .A(_03_),
    .B(_22_),
    .C(_20_),
    .D(_21_),
    .Y(_23_)
  );
  sky130_fd_sc_hd__clkinv_1 _63_ (
    .A(rst),
    .Y(_24_)
  );
  sky130_fd_sc_hd__nand4_1 _64_ (
    .A(_04_),
    .B(_07_),
    .C(_24_),
    .D(change[0]),
    .Y(_25_)
  );
  sky130_fd_sc_hd__o2111ai_1 _65_ (
    .A1(_16_),
    .A2(_11_),
    .B1(_19_),
    .C1(_25_),
    .D1(_23_),
    .Y(_38_[0])
  );
  sky130_fd_sc_hd__a21oi_1 _66_ (
    .A1(_24_),
    .A2(change[1]),
    .B1(_06_),
    .Y(_26_)
  );
  sky130_fd_sc_hd__nand3_1 _67_ (
    .A(_17_),
    .B(_20_),
    .C(_21_),
    .Y(_27_)
  );
  sky130_fd_sc_hd__nand3_1 _68_ (
    .A(_10_),
    .B(n_state[2]),
    .C(change[1]),
    .Y(_28_)
  );
  sky130_fd_sc_hd__nand3_1 _69_ (
    .A(_04_),
    .B(_24_),
    .C(change[1]),
    .Y(_29_)
  );
  sky130_fd_sc_hd__o221ai_1 _70_ (
    .A1(_10_),
    .A2(_29_),
    .B1(_26_),
    .B2(_27_),
    .C1(_28_),
    .Y(_38_[1])
  );
  sky130_fd_sc_hd__nand2_1 _71_ (
    .A(_24_),
    .B(n_state[1]),
    .Y(_30_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _72_ (
    .A1_N(_07_),
    .A2_N(_04_),
    .B1(_02_),
    .B2(_30_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__nand2_1 _73_ (
    .A(_31_),
    .B(out),
    .Y(_32_)
  );
  sky130_fd_sc_hd__nand2_1 _74_ (
    .A(_12_),
    .B(_06_),
    .Y(_33_)
  );
  sky130_fd_sc_hd__nand2_1 _75_ (
    .A(in[1]),
    .B(out),
    .Y(_34_)
  );
  sky130_fd_sc_hd__o21ai_0 _76_ (
    .A1(in[0]),
    .A2(_06_),
    .B1(_34_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__nand3b_1 _77_ (
    .A_N(out),
    .B(in[0]),
    .C(in[1]),
    .Y(_36_)
  );
  sky130_fd_sc_hd__a32oi_1 _78_ (
    .A1(_17_),
    .A2(_33_),
    .A3(_36_),
    .B1(_03_),
    .B2(_35_),
    .Y(_37_)
  );
  sky130_fd_sc_hd__nand2_1 _79_ (
    .A(_37_),
    .B(_32_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__dfxtp_1 _80_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(n_state[1])
  );
  (* src = "iiitb_vm.v:12.1-81.4" *)
  sky130_fd_sc_hd__dfxtp_1 _81_ (
    .CLK(clk),
    .D(_01_),
    .Q(out)
  );
  (* src = "iiitb_vm.v:12.1-81.4" *)
  sky130_fd_sc_hd__dfxtp_1 _82_ (
    .CLK(clk),
    .D(_38_[0]),
    .Q(change[0])
  );
  (* src = "iiitb_vm.v:12.1-81.4" *)
  sky130_fd_sc_hd__dfxtp_1 _83_ (
    .CLK(clk),
    .D(_38_[1]),
    .Q(change[1])
  );
  (* src = "iiitb_vm.v:12.1-81.4" *)
  sky130_fd_sc_hd__dfxtp_1 _84_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(n_state[2])
  );
endmodule
